### ISSUE TITLE
Limit the shown amount 

### ISSUE THREAD

**Issue by Juice2019** [DarkFox/rejseplanen-card#1]
First off, thank you for the wonderful work on the lovelace card.

Is it possible to change the number of travel options or next departures, thus showing only the next 3? etc.

Thanks in advance!

<img width="500" alt="Skærmbillede 2019-08-17 kl  11 41 14" src="https://user-images.githubusercontent.com/52465033/63209670-396c8300-c0e4-11e9-88d1-22e676499391.png">

**Comment by DarkFox** [comment]
Not at the moment, but it shouldn't be too difficult to add.

**Comment by DarkFox** [comment]
You can now limit the number of shown departures using `max_entries` starting with version 1.3.0. 👍
