### ISSUE TITLE
Feature request: "distance to stop"/ "traveltime to stop"

### ISSUE THREAD

**Issue by oz9els** [DarkFox/rejseplanen-card#4]
Discharge busses/trains within the first x minutes.

Example: I live 5 min from the bus-stop, then all buses that arrives within then next 5 minutes is not on the list.

Problem is that I live nearby a very busy bus-stop, so often I can not get to the stop, before  the next 3 buses have already left ;-)

BTW, thanks for a great looking card..

**Comment by DarkFox** [comment]
This kind of filtering should be done in the integration, not the card. Please request it in the [HA Feature Request forum](https://community.home-assistant.io/c/feature-requests).
