### ISSUE TITLE
New 1.4.0 does not look good anymore

### ISSUE THREAD

**Issue by KennethLavrsen** [DarkFox/rejseplanen-card#7]
I just upgraded this to 1.4.0

And the nice look with the graphics now looks naked with no styling and aligned to the left

Did you forget to include something in the 1.4.0 release?

I tried to refresh cache.

This is how it looks now

![image](https://user-images.githubusercontent.com/8373419/93522567-f9ed1780-f931-11ea-8dc4-fd519e0a59eb.png)

**Comment by KennethLavrsen** [comment]
And this is how the older 1.3 release looks like when I downgrade

![image](https://user-images.githubusercontent.com/8373419/93522689-29038900-f932-11ea-92ee-07765df9179e.png)

**Comment by DarkFox** [comment]
As with the other card, ensure the inclusion type is `js`, and that you've manually reloaded the page, after clicking "Reload Resources", as the CSS classes have changed.

**Comment by KennethLavrsen** [comment]
You cannot do that anymore. Home assistant deprecated that and when you install new or update something it becomes module.  You must be running Lovelace in yaml mode since you did not notice

**Comment by KennethLavrsen** [comment]
Made a test where I copied the js file into the www directory and hacked the JSON file for lovelace resources to point at url: /local/rejseplanen-card.js?v=0 like in the manual installation. The card still correctly shows the buses which means it is running and picking up date. But without the styling still.

**Comment by KennethLavrsen** [comment]
Version 1.5.2 did not resolve the lack of styling.

Eller på jysk, det kunne være meget bedre ;-)

**Comment by joernborup** [comment]
Hi...
Nice solution. Tablet next to the front door, showing how many minutes the kinds have before the bus leaves the bus stop ;-). So thanks.

But I encounter same issues as Kenneth is reporting.

/Jørn

**Comment by tpbillund** [comment]
When are the problem with the CSS being resolve, as KennethLavrsen is pointing out, I have the same issue with the style?

**Comment by DarkFox** [comment]
Unfortunately I haven't had the time to look at it yet, as I've just started at a new job. I'm hoping to look at it this weekend though.

**Comment by KennethLavrsen** [comment]
Hey. It is just a hobby. And the issue is cosmetic and a feature that is less important. Take your time. Thanks for follow up

**Comment by tpbillund** [comment]
Hi again
Can see that in my case, im looking for a CSS class called "route-Bybus-2" but that class is not in the CSS.
Im getting that info from the "route: 'Bybus 2'" in my config file for the "Rejseplanen" plugin.

I have tried to add the class under/after span.type-BUS in the rejseplanen-card.js file for the card, but after the last CSS .route-Bus- and before the route-Havnebus-

like this.
.type-custom-rejseplanen-card span[class*=" route-Bybus-2"][class$="N"] {\n          background-color: #808080;\n        }\n\n         , but nothing happens....

**Comment by tpbillund** [comment]
@DarkFox  and @KennethLavrsen 
I got it working... was playing with the Atomic-Calendar Card, and there was some style i needed to fix.
So I installed the "Lovelace card mod".

Then I was playing around and looked at the "Rejseplan card" and in my config i just added a little thing...
My code was:
`                  - type: 'custom:rejseplanen-card'
                    entity: sensor.gjellerup_klokkekildevej
                    show_scheduled_time: true
                    max_entries: 10
                    title: Næste Bybus mod Herning`

My code now, and it works...:
`                  - type: 'custom:rejseplanen-card'
                    style: |
                      ha-card {
                      }
                    entity: sensor.gjellerup_klokkekildevej
                    show_scheduled_time: true
                    max_entries: 10
                    title: Næste Bybus mod Herning`

So its just a little style thing, about ha-card, so now it looks like [https://github.com/DarkFox/rejseplanen-card/issues/7#issuecomment-694471519](The Image from Kenneth)

**Comment by DurgNomis-drol** [comment]
I think i have found the error. When i delete ".type-custom-" in your css class it works again for me and shows it correct. 

Please correct me if im wrong

I have made an pull request

**Comment by DarkFox** [comment]
> I think i have found the error. When i delete ".type-custom-" in your css class it works again for me and shows it correct.
> 
> Please correct me if im wrong
> 
> I have made an pull request

Thanks, I've merged your fix and released a new version.

**Comment by KennethLavrsen** [comment]
Fix works. But your updates broke the stog variant. See my update to the bug report I made there.

**Comment by KennethLavrsen** [comment]
Confirmed fixed, and with the last update also the stog variant works. Thanks for the fixes guys

**Comment by DarkFox** [comment]
Thanks for everyone's help (and gentle push) to get this fixed. 👍
